---
- name: Copy dotfile
  copy:
    src: "{{ item }}"
    dest: "{{ desktop_user_vars.dir }}/.{{ item }}"
  with_items: "{{ copied_dotfiles }}"
- name: Template dotfile
  template:
    src: "{{ item }}"
    dest: "{{ desktop_user_vars.dir }}/.{{ item }}"
  with_items: "{{ templated_dotfiles }}"

