---
- name: Create directories
  file:
    state: directory
    path: "{{ desktop_user_vars.dir }}/{{ item }}"
  with_items: "{{ directories_for_dotfiles }}"
- name: Copy dotfile
  copy:
    src: "{{ item | regex_replace('^\\.', '') }}"
    dest: "{{ desktop_user_vars.dir }}/{{ item }}"
  with_items: "{{ copied_dotfiles }}"
- name: Template dotfile
  template:
    src: "{{ item | regex_replace('^\\.', '') }}"
    dest: "{{ desktop_user_vars.dir }}/{{ item }}"
  with_items: "{{ templated_dotfiles }}"
